# Upload the caller repo's Python package to pypi.org.
#
# TODO: This is actually just a test workflow right now and doesn't upload to
# pypi at all.
name: Publish to pypi.org
on:
  workflow_call:
    secrets:
      PYPI_API_TOKEN:
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: pip install httpie
      - run: http https://qa.hyp.is/${{ secrets.PYPI_API_TOKEN }}
